name: openfga
description: OpenFGA SDK for Dart
version: 0.0.0-beta.1
repository: https://github.com/amondnet/openfga.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  grpc: ^3.0.0
  protobuf: ^2.0.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
